"""Add impermanent loss to metrics

Revision ID: 4a3d136863ec
Revises: b5dd3ee12f61
Create Date: 2025-07-28 14:57:13.212176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a3d136863ec'
down_revision: Union[str, Sequence[str], None] = 'b5dd3ee12f61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position_metrics', sa.Column('impermanent_loss_percent', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('position_metrics', 'impermanent_loss_percent')
    # ### end Alembic commands ###
